package day3_exception.throwException;

public class Throw {
    public static void main(String[] args) {
        throw new RuntimeException("문제가 발생했음!"); // 여기서 예외 발생
    }
}
